image:
          db:
             repository: devopseasylearning2021/s4-db
             tag: "v87.0.0"
          ui:
             repository: devopseasylearning2021/s4-ui
             tag: "v88.0.0"
          auth:
             repository: devopseasylearning2021/s4-auth
             tag: "v89.0.0"
          weather:
             repository: devopseasylearning2021/s4-weather
             tag: "v180.0.0"
